server:
  port: 8080

spring:
  application:
    name: trackfinder
    title: track-finder
    version: 1.0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trackfinder-db
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect