server:
  port: 8080

spring:
  application:
    name: trackfinder
    title: track-finder
    version: 1.0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL_DB}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

spotify-api:
  client-id: ${API_CLIENT_ID}
  client-secret: ${API_CLIENT_SECRET}
  grant-type: client_credentials
  url-auth: https://accounts.spotify.com/api/token
  url-api: https://api.spotify.com/v1

cors:
  allowed-origins: ${URL_FRONTEND}

springdoc:
  version: 1.0.0
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tagsSorter: alpha
    defaultModelsExpandDepth: -1
    tryItOutEnabled: true
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json
  show-actuator: false
  group-configs:
    - group: track-api
      paths-to-match: /codechallenge/**